CREATE TABLE users (
  UserID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(150) NOT NULL,
  Email VARCHAR(254) UNIQUE NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Role VARCHAR(20) NOT NULL
);

CREATE TABLE Facility (
  FacilityID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  Type VARCHAR(50) NOT NULL,
  Status VARCHAR(20) NOT NULL
);

CREATE TABLE Reservation (
  ReservationID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  FacilityID INT NOT NULL,
  Date DATETIME NOT NULL,
  StartTime TIME NOT NULL,
  EndTime TIME NOT NULL,
  Participants INT NOT NULL,
  Purpose VARCHAR(250),

  FOREIGN KEY (UserID) REFERENCES users(UserID) ON DELETE CASCADE,
  FOREIGN KEY (FacilityID) REFERENCES Facility(FacilityID) ON DELETE CASCADE
);

CREATE TABLE Maintenance_Request (
  RequestID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  FacilityID INT NOT NULL,
  StaffID INT NULL,
  Description TEXT NOT NULL,
  Status VARCHAR(20) NOT NULL,
  ReportDate DATETIME NOT NULL,
  IssueType VARCHAR(100) NOT NULL,
  Severity VARCHAR(100) NOT NULL,

  FOREIGN KEY (UserID) REFERENCES users(UserID) ON DELETE CASCADE,
  FOREIGN KEY (FacilityID) REFERENCES Facility(FacilityID) ON DELETE CASCADE,
  FOREIGN KEY (StaffID) REFERENCES users(UserID) ON DELETE SET NULL
);

CREATE TABLE Penalty (
  PenaltyID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  Description TEXT NOT NULL,
  DateHour DATETIME NOT NULL,

  FOREIGN KEY (UserID) REFERENCES users(UserID) ON DELETE CASCADE
);